Create views for user and post views
GutemaG/Ruby-blog-app pull request #6
Opened 2023-04-05 18:38 UTC by GutemaG

## Create views for user and post views

### Project requirements
- Implement the 
![Screenshot from 2023-04-05 21-35-25](https://user-images.githubusercontent.com/24788565/230174040-d5199c10-40cd-408e-9c4b-15b15b30f6d5.png)
design from the sneak peek the  wireframes. (:heavy_check_mark: )

    - Styling is nice to have but focus on making sure everything functions first. (Note: Ignore login logic, you would be using Devise in coming milestone)
-

- Create views for show and index for each post and user controller

2023-04-05 18:54 UTC, julie-ify requested changes
## Hi @GutemaG,

Good job so far!

## Highlights!
- Nice looking design ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 18:54 UTC, julie-ify commented on app/views/users/show.html.erb
> +      <% @user.posts.each do |post| %>
- [ ] The posts that should be rendered in this user show page are the recent posts of the user. Kindly refactor this view to use the `recent_three_posts` in your User model.

  ```
  @user.recent_three_posts.each do |post|
    ...
  ```

2023-04-05 18:54 UTC, julie-ify commented on app/views/posts/index.html.erb
> +        <% post.comments.each do |comment| %>
- [ ] The comments to be rendered on this post index page should use the recent comments method you have in the Post model, kindly do that.

2023-04-05 18:54 UTC, julie-ify commented on app/views/users/index.html.erb
> -</ul>
- [ ] Good job styling the user element on the page, however, you need to center the elements on the page to follow [the wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_root_users.png). Kindly also make it larger to cover more width on the page.

  ![isos](https://user-images.githubusercontent.com/81468675/230176525-758b8b53-4a74-4ec6-94a3-685377b67900.jpg)

2023-04-05 18:54 UTC, julie-ify commented on app/views/users/show.html.erb
> +  </div>
- [ ] Kindly center the elements as well to match [the wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_page.png?token=GHSAT0AAAAAACBA7J7KGYMVA3EGE46DPJMEZBN2DTQ) and make them wider.

  ![image](https://user-images.githubusercontent.com/81468675/230176877-290b4ddd-520d-4708-960c-ddc95b0c72ca.png)

2023-04-05 18:54 UTC, julie-ify commented on app/views/posts/index.html.erb
> +  <button class="btn btn-secondary btn-sm mt-5">Pagination comming soon</button>
- [ ] Kindly center the elements to match [the wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/blog-app/images/blog_user_all_posts.png?token=GHSAT0AAAAAACBA7J7KYPXEYKZOH5JANANQZBN2FFQ).

  ![image](https://user-images.githubusercontent.com/81468675/230177519-6dd653ae-b472-4be6-bf4b-43c018572d5f.png)

2023-04-05 18:54 UTC, julie-ify commented on app/views/posts/show.html.erb
> +</div>
- [ ] Kindly center the elements to match [the wireframe](https://github.com/microverseinc/curriculum-rails/raw/main/blog-app/images/blog_single_post.png).

  ![image](https://user-images.githubusercontent.com/81468675/230177233-9fc48143-bdfb-4813-a399-50e986a1929a.png)

2023-04-06 19:37 UTC, vickymarz approved these changes
Hi @GutemaG, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request is following the Git Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 

<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-06 19:38 UTC, merged